export const SELECT_TYPE = "SELECT_TYPE";

export const REQUEST_RESTAURANTS = "REQUEST_RESTAURANTS";

export const RECEIVE_RESTAURANTS = "RECEIVE_RESTAURANTS";

export const SET_ERROR_RESTAURANTS = "SET_ERROR_RESTAURANTS";
